{% set release =  '4.' + (tag|string).split('.')[1] if tag|count('.') > 1 else tag %}
{% set site_generate_registry = 'registry.stage.redhat.io' if 'rc' in tag else 'registry.redhat.io' %}

{% set ztp_images = ['registry.redhat.io/rhel9/support-tools', 'quay.io/mavazque/gitea:1.17.3', site_generate_registry + '/openshift4/ztp-site-generate-rhel8:v' + OPENSHIFT_TAG|string, 'registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9:v2.13'] %}

apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  platform:
    graph: false
{% if version in ['ci', 'nightly'] %}
    release: registry.ci.openshift.org/ocp/release:{{ tag }}
{% else %}
    channels:
    - name: {{ 'candidate' if 'rc' in tag else version }}-{{ release }}
{% if tag|count('.') > 1 %}
      minVersion: {{ (disconnected_extra_release or tag)|min_ocp_version(tag) }}
      maxVersion: {{ (disconnected_extra_release or tag)|max_ocp_version(tag) }}
{% endif %}
{% endif %}
    architectures:
#   - multi
    - amd64
  additionalImages:
{% for image in ztp_images + extra_images|default([]) %}
  - name: {{ image }}
{% endfor %}
{% set operators = disconnected_operators|default([]) + disconnected_certified_operators|default([]) + disconnected_community_operators|default([]) + disconnected_marketplace_operators|default([]) %}
{% if operators %}
  operators:
{% if disconnected_operators|default([]) %}
{% set catalog = 'quay.io/prega/prega-operator-index' if prega|default(False) else 'registry.redhat.io/redhat/redhat-operator-index' %}
  - catalog: {{ catalog }}:{{ prega_tag or disconnected_operators_version or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}{# Comment: Support old syntax #}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% if disconnected_certified_operators|default([]) %}
  - catalog: registry.redhat.io/redhat/certified-operator-index:{{ disconnected_certified_operators_version or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_certified_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% if disconnected_community_operators|default([]) %}
  - catalog: registry.redhat.io/redhat/community-operator-index:{{ disconnected_community_operators_version or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_community_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% if disconnected_marketplace_operators|default([]) %}
  - catalog: registry.redhat.io/redhat/redhat-marketplace-index:{{ disconnected_marketplace_operators_version or "v%s" % OPENSHIFT_TAG }}
    packages:
{% for package in disconnected_marketplace_operators %}
{% if package.name is defined %}
    - name: {{ package.name }}
{% else %}
    - name: {{ package }}
{% endif %}
{% if package.minVersion is defined %}
      minVersion: {{ package.minVersion }}
{% endif %}
{% if package.maxVersion is defined %}
      maxVersion: {{ package.maxVersion }}
{% endif %}
{% if package.channels is defined and package.channels|length > 0 %}
      channels:
{% for channel in package.channels %}
      - name: {{ channel.name }}
{% if channel.minVersion is defined %}
        minVersion: {{ channel.minVersion }}
{% endif %}
{% if channel.maxVersion is defined %}
        maxVersion: {{ channel.maxVersion }}
{% endif %}
{% endfor %}
{% endif %}
{% endfor %}
{% endif %}
{% endif %}
{% if disconnected_extra_catalogs|default([]) %}
{% for catalog_image in disconnected_extra_catalogs %}
  - catalog: {{ catalog_image }}
{% endfor %}
{% endif %}
