---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "workers"
  namespace: "ztp-policies"
spec:
  bindingRules:
    group-du-sno: ""
    logicalGroup: "active"
    hardware-type: "hw-type-platform-1"
    provider: "kcli"
  mcp: worker
  remediationAction: inform
  sourceFiles:
  - fileName: DisableSnoNetworkDiag.yaml
    policyName: "group-policy"
  - fileName: DisableOLMPprof.yaml # wave 10
    policyName: "group-policy"
  - fileName: SriovOperatorConfig.yaml
    policyName: "group-policy"
    # Using hub templating to obtain if the SR-IOV card is supported for this hw type
    spec:
      disableDrain: true
      enableOperatorWebhook: false
  - fileName: PerformanceProfile.yaml
    # Using hub templating to obtain if the tunning config for this hw type
    policyName: "group-policy"
    metadata:
      annotations:
        kubeletconfig.experimental: |
          {"topologyManagerScope": "pod",
           "systemReserved": {"memory": "3Gi"}
          }
    spec:
      cpu:
        isolated: "4-15"
        reserved: "0-3"
      hugepages:
        defaultHugepagesSize: 1G
        pages:
        - count: 16
          size: 1G
      numa:
        topologyPolicy: single-numa-node
      realTimeKernel:
        enabled: false
      globallyDisableIrqLoadBalancing: false
      # WorkloadHints defines the set of upper level flags for different type of workloads.
      # The configuration below is set for a low latency, performance mode.
      workloadHints:
        realTime: true
        highPowerConsumption: false
        perPodPowerManagement: false
  - fileName: TunedPerformancePatch.yaml
    policyName: "group-policy"
    spec:
      profile:
      - name: performance-patch
        data: |
          [main]
          summary=Configuration changes profile inherited from performance created tuned
          include=openshift-node-performance-openshift-node-performance-profile
          [sysctl]
          # When using the standard (non-realtime) kernel, remove the kernel.timer_migration override from the [sysctl] section
          # kernel.timer_migration=0
          [scheduler]
          group.ice-ptp=0:f:10:*:ice-ptp.*
          group.ice-gnss=0:f:10:*:ice-gnss.*
          [service]
          service.stalld=start,enable
          service.chronyd=stop,disable
  - fileName: SriovNetwork.yaml
    # Using hub templating to obtain the SR-IOV config of each SNO
    policyName: "sites-policy"
    metadata:
      name: "sriov-nw-du-netdev"
    spec:
      ipam: '{"type": "host-local","ranges": [[{"subnet": "192.168.100.0/24"}]],"dataDir":
    "/run/my-orchestrator/container-ipam-state-1"}'
      resourceName: enp4s0
      spoofChk: "off"
      trust: "on"
  - fileName: SriovNetworkNodePolicy.yaml
    policyName: "sites-policy"
    complianceType: mustonlyhave
    metadata:
      name: enp4s0
    spec:
      deviceType: netdevice
      needVhostNet: false
      mtu: 1500
      linkType: eth
      isRdma: false
      nicSelector:
        vendor: "8086"
        deviceID: "10c9"
        pfNames:
        - enp4s0
      numVfs: 2
      resourceName: enp4s0
