---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: odf-storagecluster-ceph-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: openshift-storage.rbd.csi.ceph.com
