---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  name: odf-operator
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace
status:
  state: AtLatestKnown
