{% set spoke = spokes[index] %}
{% set virtual_nodes_number = spoke.get('virtual_nodes', 0) %}

{% set nodes = spoke.get('baremetal_nodes', []) %}

{% if virtual_nodes_number > 0 %}
{% set extra_nodes = [] %}
{% for num in range(0, virtual_nodes_number) %}
{% do extra_nodes.append({}) %}
{% endfor %}
{% set nodes = extra_nodes + nodes %}
{% endif %}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ spoke.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: {{ spoke.name }}
stringData:
  .dockerconfigjson: '${PULLSECRET}'
  type: kubernetes.io/dockerconfigjson
---
{% for node in nodes %}
{% set num = loop.index0 %}
apiVersion: v1
data:
  password: {{ (node.bmc_password|default(bmc_password))|string|base64 }}
  username: {{ (node.bmc_user|default(bmc_user))|string|base64 }}
kind: Secret
metadata:
  name: {{ cluster }}-ztp-{{ spoke.name }}-bmc-secret-{{ num }}
  namespace: {{ spoke.name }}
type: Opaque
---
{% endfor%}
