# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export KUBECONFIG=/root/kubeconfig.{{ cluster }}
export PATH=/usr/local/bin:/root/bin:$PATH
export REGISTRY_PASSWORD={{ disconnected_password }}
export REGISTRY_USER={{ disconnected_user }}
export PYTHONUNBUFFERED=true
export AI_URL=127.0.0.1:8090
